services:
  artifact:
    image: ${IMAGE}
    ports:
      - "8443:443"
    volumes:
      - ./certs/:/usr/share/nginx/certs/:z
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:z
      - ./index.html:/usr/share/nginx/html/index.html:z
