services:
  artifact:
    image: ${IMAGE}
    ports:
      - "8443:443"
    volumes:
      - ${CERTIFICATE_PATH}:/usr/share/nginx/certs/ear-http.crt:z
      - ${KEY_PATH}:/usr/share/nginx/certs/ear-http.pem:z
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:z
      - ./index.html:/usr/share/nginx/html/index.html:z
