services:
  artifact:
    image: ${IMAGE}
    ports:
      - ${EAR_PORT}:443
    volumes:
      - ${CERTIFICATE_PATH}:/usr/share/nginx/certs/ear-http.crt:z
      - ${KEY_PATH}:/usr/share/nginx/certs/ear-http.pem:z
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:z
